#!/usr/bin/env python3
#
# This file is part of the sporetrap analysis scripts.
#
# Copyright (c) 2024 Jason Toney
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""
    This script counts the number of microspheres captured by using a sticky trap.
    Input: CSV file containing list of ROIs generated by our analysis with ImageJ.
    Output: CSV file containing count of microspheres for each position in a trap.
"""

import csv
import os
import sys
from math import pi


# 135 images = 1 full sticky trap
def analyze_sporetraps(folder):
    """Total the counts for each sticky trap and write the results to an output file."""
    release = " - ".join(os.path.basename(os.path.dirname(folder)).split(" - ")[0:-1])
    trap = os.path.basename(folder)
    green_results = [
        csv_handler(os.path.join(folder, csv_file), "Green")
        for csv_file in os.listdir(folder)
    ]
    # Red microsphere counts *may* not be present - if so fill em with zeroes
    if os.path.exists(folder.replace("Green", "Red")):
        red_results = [
            csv_handler(os.path.join(folder.replace("Green", "Red"), csv_file), "Red")
            for csv_file in os.listdir(folder.replace("Green", "Red"))
        ]
    else:
        red_results = [0] * 135
    # make sure each trap has the correct number of images, 135 for each sticky trap
    green_images = len(green_results)
    red_images = len(red_results)
    if green_images != 135:
        sys.exit(
            f"ERROR: {release}: Trap {trap} contains {green_images} images of Green microspheres."
        )
    if red_images != 135:
        sys.exit(
            f"ERROR: {release}: Trap {trap} contains {red_images} images of Red microspheres."
        )
    # Output data and file headers
    sporetrap_data = [trap]
    headers = [
        "Trap",
        "Microspheres (G)",
        "Microspheres (R)",
        "Notes",
    ]
    green_count = sum(green_results)
    red_count = sum(red_results)
    sporetrap_data.extend([green_count, red_count])
    # Write the results to the output file
    outfile = f"results/{release}.csv"
    write_headers = True
    if os.path.exists(outfile):
        write_headers = False
    with open(
        outfile,
        "a",
        newline="",
        encoding="utf-8",
    ) as csv_outfile:
        csv_writer = csv.writer(csv_outfile)
        if write_headers:
            csv_writer.writerow(headers)
        csv_writer.writerow(sporetrap_data)


# handle csv datasets
def csv_handler(filename, color):
    """Count the microspheres and exclude any bad ROIs."""
    counted = 0
    with open(filename, "r", encoding="utf-8") as csv_file:
        csv_reader = csv.DictReader(csv_file, delimiter=",")
        for row in csv_reader:
            counted += is_particle(row, color)
    return counted


# Filter out bad ROIs | Start here: 1 pixel = 8.067 um^2
def is_particle(row, color):
    """Returns true if the ROI should be counted."""
    area = float(row["Area"])
    feret = float(row["Feret"])
    min_feret = float(row["MinFeret"])
    roundness = float(row["Round"])
    # minimum area = 90% of area of a circle with diameter=min_feret
    min_area = (pi * (min_feret / 2) ** 2) * 0.9
    if color == "Green":
        min_diameter = 10
        particle = feret >= min_diameter and area >= min_area and roundness >= 0.65
    else:
        min_diameter = 150
        particle = feret >= min_diameter
    return particle


def main(folder):
    """Execute main objective."""
    os.chdir(os.path.dirname(__file__))
    analyze_sporetraps(folder)


if __name__ == "__main__":
    if len(sys.argv) == 2:
        main(sys.argv[1])
    else:
        sys.exit(f"Usage: python3 {__file__} [FILE]")
