#!/usr/bin/env python3
#
# This file is part of the sporetrap analysis scripts.
#
# Copyright (c) 2024 Jason Toney
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""
    This script counts the number of microspheres captured by using a sticky trap.
    Input: CSV file containing list of ROIs generated by our analysis with ImageJ.
    Output: CSV file containing count of microspheres for each position in a trap.
"""

import csv
import os
import sys
from math import pi


# 135 images = 1 full sticky trap
def analyze_sporetraps(filename):
    """Total the counts for each sticky trap and write the results to an output file."""
    release = " - ".join(os.path.basename(os.path.dirname(filename)).split(" - ")[0:-1])
    trap = os.path.basename(filename).split(".")[0]
    green_results = csv_handler(
        f"ImageJ/sporetraps/results/{release} - Green/{trap}.csv"
    )
    # Red microsphere counts *may* not be present - if so fill em with zeroes
    if os.path.exists(f"ImageJ/sporetraps/results/{release} - Red/{trap}.csv"):
        red_results = csv_handler(
            f"ImageJ/sporetraps/results/{release} - Red/{trap}.csv"
        )
    else:
        red_results = [0] * 135
    # make sure each trap has the correct number of images, 135 for each sticky trap
    green_images = len(green_results)
    red_images = len(red_results)
    if green_images != 135:
        sys.exit(
            f"ERROR: {release}: Trap {trap} contains {green_images} images of Green microspheres."
        )
    if red_images != 135:
        sys.exit(
            f"ERROR: {release}: Trap {trap} contains {red_images} images of Red microspheres."
        )
    # Output data and file headers
    sporetrap_data = [trap]
    headers = [
        "Trap",
        "Microspheres (G)",
        "Microspheres (R)",
        "Notes",
    ]
    green_count, red_count = 0, 0
    for result in green_results:
        green_count += result
    for result in red_results:
        red_count += result
    sporetrap_data.extend([green_count, red_count])
    # Write the results to the output file
    outfile = f"results/{release}.csv"
    write_headers = True
    if os.path.exists(outfile):
        write_headers = False
    with open(
        outfile,
        "a",
        newline="",
        encoding="utf-8",
    ) as csv_outfile:
        csv_writer = csv.writer(csv_outfile)
        if write_headers:
            csv_writer.writerow(headers)
        csv_writer.writerow(sporetrap_data)


# handle csv datasets
def csv_handler(filename):
    """Count the microspheres and drop any bad ROIs."""
    release = os.path.basename(os.path.dirname(filename))
    color = release.split(" - ")[-1]
    trap = os.path.basename(filename).split(".")[0]
    with open(filename, "r", encoding="utf-8") as csv_file:
        csv_reader = csv.DictReader(csv_file, delimiter=",")
        image_data = []
        counted = 0
        current_slice = 1
        for row in csv_reader:
            imagenum = int(row["Slice"])
            feret = float(row["Feret"])
            min_feret = float(row["MinFeret"])
            # calculate totals for each image
            if imagenum == current_slice:
                if not is_artifact(row, color):
                    counted += 1
                    if color == "Red" and (feret > 425 or min_feret > 425):
                        print(
                            f"Large Red Microsphere located in Release: {release} Trap: {trap} Image: {imagenum}"
                        )
            else:
                # hit the next slice, store the count
                image_data.append(counted)
                current_slice += 1
                if is_artifact(row, color):
                    counted = 0
                else:
                    counted = 1
                    if color == "Red" and (feret > 425 or min_feret > 425):
                        print(
                            f"Large Red Microsphere located in Release: {release} Trap: {trap} Image: {imagenum}"
                        )
        # outside of the loop
        image_data.append(counted)
    return image_data


# Filter out bad ROIs | Start here: 1 pixel = 8.067 um^2
def is_artifact(row, color):
    """Returns true if the ROI should not be counted."""
    # TODO: Fix size bounds for Red microspheres, use wide range for now
    area = float(row["Area"])
    feret = float(row["Feret"])
    min_feret = float(row["MinFeret"])
    # minimum area = 90% of area of a circle with diameter=min_feret
    min_area = (pi * (min_feret / 2) ** 2) * 0.9
    if color == "Green":
        min_diameter = 10
    else:
        min_diameter = 150
    return (feret < min_diameter and min_feret < min_diameter) or area < min_area


def main(filename):
    """Execute main objective."""
    os.chdir(os.path.dirname(__file__))
    analyze_sporetraps(filename)


if __name__ == "__main__":
    if len(sys.argv) == 2:
        main(sys.argv[1])
    else:
        sys.exit(f"Usage: python3 {__file__} [FILE]")
